github: justbytecode
patreon: velocitycli


# Optional platforms (uncomment when ready)
# open_collective: velocity
# ko_fi: velocitycli
# polar: velocity
# liberapay: velocitycli

# Custom links (up to 4)
custom:
  - https://buymeacoffee.com/velocitycli
  - https://razorpay.me/@manipal

